name: GitHub to Oracle VM - Frontend pub
run-name: ${{ github.actor }} is send front to production 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
         #14.x, 16.x, 
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn
    - name: Build
      run: |
        yarn build
    - name: Testing build
      run: ls ./dist
      
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.ORACLEVMPRIV}} 
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
    - name: Adding Known Hosts
      run: ssh-keyscan -H ${{ secrets.SSH_SERVER }} >> ~/.ssh/known_hosts
    - name: Deploy with rsync
      run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_SERVER }}:/var/www/html/blitzkrieg.jeanpaullopes.pro.br/  
    - name: Finishing and going home
      run: echo "🍏 This job's status is ${{ job.status }}."
